version: "3.9"
services:
  chall:
    build:
      context: ./chall
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: any
    ports:
      - '80:80'
    environment:
      - SITE=https://msgme.be.ax
      - FLAG=corctf{REDACTED}
      - ADMIN_PASSWORD=REDACTED
      - SESSION_SECRET=REDACTED
    read_only: true